### ISSUE TITLE
how to install and use "u-boot" on Ubuntu? 

### ISSUE THREAD

**Issue by sanderjo** [maquefel/licheerv-boot-build#3]
the README says "U-boot commands (i haven't put a u-boot env yet - have to decide what i really need)". 

How should I install and start u-boot on Ubuntu? I installed 
```
u-boot-tools
u-boot-menu
```
but they don't provide a uboot nor u-boot executable?

**Comment by maquefel** [comment]
That's the console commands for LicheeRV itselfs, prepare sdcard, insert it, then connect, ttl->usb cable to LicheeRV UART0 (be carefull) and wait for u-boot prompt.

**Comment by sanderjo** [comment]
> then connect, ttl->usb cable to LicheeRV UART0

Ah, yes ... this busybox image does not work with keyboard and HDMI, right?

Where is the UART0 on the Dock (or board)? 
And do you have a pointer to a ttl->usb cable (on AliExpress maybe)?

**Comment by maquefel** [comment]
> Ah, yes ... this busybox image does not work with keyboard and HDMI, right?

That's correct - i've just received my RV Dock so i didn't test to try to bringup HDMI.

> Where is the UART0 on the Dock (or board)?

![image](https://user-images.githubusercontent.com/1780932/150341178-a9f6071c-4214-4ca7-ab4d-ffa782c21013.png)

> And do you have a pointer to a ttl->usb cable (on AliExpress maybe)?

I am using TTL-232R-3V3-WE.
Something like this one https://aliexpress.ru/item/1005003198254685.html - you strictly need 3v3 version.

**Comment by sanderjo** [comment]
> That's correct - i've just received my RV Dock so i didn't test to try to bringup HDMI.

Is it OK if I create an issue for that ... so that if/when you make that working, you can let it know via that issue notification?
